import 'dart:io';
import 'dart:math';

class SuggestionData {
  static List<String> jobData = [
    "Acentacı",
    "Aşçı",
    "Aktör",
    "Ambulans şoförü",
    "Anahtarcı",
    "Analist",
    "Animatör",
    "Araba yıkayıcısı",
    "Arabulucu",
    "Araştırmacı",
    "Arıcı",
    "Arkeolog",
    "Asansörcü",
    "Astrofizikçi",
    "Astrolog",
    "Ayakkabı tamircisi",
    "Ayakkabıcı",
    "Baharatçı",
    "Bakkal",
    "Balıkçı",
    "Balerin",
    "Bankacı",
    "Banker",
    "Barmen",
    "Basketbolcu",
    "Benzinci",
    "Berber",
    "Besteci",
    "Bilgisayar mühendisi",
    "Bilgisayar programcısı",
    "Bilgisayar tamircisi",
    "Bilim insanı",
    "Bilirkişi",
    "Bisikletçi",
    "Biyografi yazarı",
    "Boyacı",
    "Bulaşıkçı",
    "Bütçe uzmanı",
    "Bebek bakıcısı",
    "Bilgi İşlemci",
    "Camcı",
    "Cerrah",
    "Çamaşırcı",
    "Çantacı",
    "Çaycı",
    "Çevirmen",
    "Çevrebilimci",
    "Çevre mühendisi",
    "Çeyizci",
    "Çıkıkçı",
    "Çiçekçi",
    "Çiftçi",
    "Çiftlik işletici",
    "Çikolatacı",
    "Çilingir",
    "Çinici",
    "Çitçi",
    "Çoban",
    "Çocuk doktoru",
    "Çöpçü",
    "Dadı",
    "Danışman",
    "Dansöz",
    "Davulcu",
    "Dedektif",
    "Değirmen işçisi",
    "Değirmenci",
    "Demirci",
    "Demiryolu işçisi"
        "Denetleyici",
    "Denizci",
    "Depocu",
    "Derici",
    "Dil ve Konuşma Terapisti",
    "Diş hekimi",
    "Diyetisyen",
    "Doğalgazcı",
    "Doğramacı",
    "Doğum uzmanı",
    "Dokumacı",
    "Doktor",
    "Dondurmacı",
    "Dökümcü",
    "Döşemeci",
    "Dövizci",
    "Dublajcı",
    "Duvarcı",
    "Dansçı",
    "Ebe",
    "Eczacı",
    "Eczacı kalfası",
    "Editör"
        "Ekonomist",
    "Elektrik mühendisi",
    "Elektronik mühendisi",
    "Elektrik-Elektronik mühendisi",
    "Elektronik ve Haberleşme mühendisi",
    "Elektrikçi",
    "Eleştirmen",
    "Emlakçı",
    "Endüstri mühendisi",
    "Endüstri sistemleri mühendisi",
    "Enstrüman imalatçısı",
    "Ergonomist",
    "Eskici",
    "Estetisyen",
    "Fabrika işçisi",
    "Falcı",
    "Fermantasyon işçisi",
    "Fıçıcı",
    "Fırıncı",
    "Figüran",
    "Film yapımcısı",
    "Film yönetmeni",
    "Filozof",
    "Finansör",
    "Fizikçi",
    "Fizyonomist",
    "Fizyoterapist",
    "Forklift operatörü",
    "Fotoğrafçı",
    "Futbolcu",
    "Gardiyan",
    "Galerici",
    "Garson",
    "Gazeteci",
    "Gelir uzmanı",
    "Gemici",
    "Genetik mühendisi",
    "Gıda mühendisi",
    "Gitarist",
    "Gondolcu",
    "Gökbilimci",
    "Göz doktoru",
    "Gözetmen",
    "Gözlükçü",
    "Grafik Tasarımcısı",
    "Greyder operatörü",
    "Gündelikçi",
    "Güzellik uzmanı",
    "Hakem",
    "Halıcı",
    "Hamal",
    "Hamamcı",
    "Haritacı",
    "Harita mühendisi",
    "Hastabakıcı",
    "Hattat",
    "Hayvan bakıcısı",
    "Hemşire",
    "Heykeltıraş",
    "Hırdavatçı",
    "Hidrolikçi",
    "Hizmetçi",
    "Hokkabaz",
    "Host",
    "Hostes",
    "Hukukçu",
    "Hurdacı",
    "Irgat",
    "İç mimar",
    "İğneci",
    "İhracatçı",
    "İktisatçı",
    "İlahiyatçı",
    "İllüzyonist",
    "İmam",
    "İnsan kaynakları uzmanı",
    "İnşaat mühendisi",
    "İnşaatçı",
    "İstatistikçi",
    "İşletmeci",
    "İşletme mühendisi",
    "İşportacı",
    "İş ve Uğraşı Terapisti",
    "İtfaiyeci",
    "Jeofizik mühendisi",
    "Jeoloji mühendisi",
    "Jeolog",
    "Jeomorfolog",
    "Jinekolog",
    "Jimnastikçi",
    "Jokey",
    "Kâğıtçı",
    "Kahveci",
    "Kâhya",
    "Kalaycı",
    "Kalıpçı",
    "Kaloriferci",
    "Kameraman",
    "Kamyoncu",
    "Kapı satıcısı",
    "Kapıcı",
    "Kaportacı",
    "Kaptan",
    "Kardiyolog",
    "Karikatürist",
    "Kasap",
    "Kasiyer",
    "Kâtip",
    "Kayıkçı",
    "Kaynakçı",
    "Kazıcı",
    "Kebapçı",
    "Kemancı",
    "Kırtasiyeci",
    "Kimyager",
    "Kimya mühendisi",
    "Kitapçı",
    "Klarnetçi",
    "Koleksiyoncu",
    "Komedyen",
    "Koruma görevlisi",
    "Kömürcü",
    "Köpek eğiticisi",
    "Köşe yazarı",
    "Kuaför",
    "Kuşçu",
    "Kumaşçı",
    "Kuru temizlemeci",
    "Kuruyemişçi",
    "Kurye",
    "Kuşbilimci",
    "Kuyumcu",
    "Kürkçü",
    "Kütüphaneci",
    "Lokantacı",
    "Madenci",
    "Maketçi",
    "Makinist",
    "Makine mühendisi",
    "Makyajcı",
    "Manav",
    "Manifaturacı",
    "Manikürcü",
    "Manken",
    "Marangoz",
    "Masör",
    "Masöz",
    "Matbaacı",
    "Matematikçi",
    "Matkapçı",
    "Medya Planlama Uzmanı",
    "Memur",
    "Menajer",
    "Mermerci",
    "Metalurji mühendisi",
    "Meteoroloji uzmanı",
    "Metin yazarı",
    "Mevsimlik işçi",
    "Meydancı",
    "Meyhaneci",
    "Mezarcı",
    "Mikrobiyolog",
    "Mimar",
    "Mobilyacı",
    "Modacı",
    "Model",
    "Montajcı",
    "Motor tamircisi",
    "Muhabir",
    "Muhasebeci",
    "Muhtar",
    "Mübaşir",
    "Müezzin",
    "Müfettiş",
    "Müteahhit",
    "Mütercim",
    "Müzik yönetmeni",
    "Müzisyen",
    "Nakışçı",
    "Nakliyeci",
    "Nalbur",
    "Oduncu",
    "Operatör",
    "Opera sanatçısı",
    "Orman mühendisi",
    "Otelci",
    "Oto elektrikçisi",
    "Oto lastik tamircisi",
    "Oto tamircisi",
    "Oto yedek parçacı",
    "Overlokçu",
    "Oyuncu",
    "Oyun yazarı",
    "Oyuncakçı",
    "Öğretmen",
    "Öğretim elemanı",
    "Özel şoför",
    "Palyaço",
    "Pandomimci",
    "Pansiyoncu",
    "Pansumancı",
    "Park bekçisi",
    "Pencereci",
    "Perukçu",
    "Peyzaj mimarı",
    "Peyzaj teknikeri",
    "Pilot",
    "Piyanist",
    "Pompacı",
    "Postacı",
    "Psikiyatr",
    "Psikolog",
    "Psikolojik danışmanlık ve rehberlik",
    "Paramedik",
    "Radyolog",
    "Reklamcı",
    "Ressam",
    "Rot balansçı",
    "Radyoloji teknisyeni/teknikeri",
    "Saat tamircisi",
    "Saatçi",
    "Sağlık teknisyeni",
    "Sahil koruma",
    "Saksofoncu",
    "Sanat yönetmeni",
    "Sanayici",
    "Satış elemanı",
    "Sekreter",
    "Senarist",
    "Serbest muhasebeci mali müşavir",
    "Ses teknisyeni",
    "Seyis",
    "Sigortacı",
    "Silahçı",
    "Simyacı",
    "Sistem mühendisi",
    "Sistem yöneticisi",
    "Soğuk demirci",
    "Sokak çalgıcısı",
    "Sosyal hizmet uzmanı",
    "Sosyolog",
    "Spiker",
    "Striptizci",
    "Su tesisatçısı",
    "Sucu",
    "Sunucu",
    "Sünnetçi",
    "Sütçü",
    "Şair",
    "Şapkacı",
    "Şarap üreticisi",
    "Şarkıcı",
    "Şarkı sözü yazarı",
    "Şarküter",
    "Şekerci",
    "Şemsiyeci",
    "Şoför",
    "Şarapçı",
    "Şehir Plancısı",
    "Taksici",
    "Tarım işçisi",
    "Tarihçi",
    "Tasarımcı",
    "Tatlıcı",
    "Tekniker",
    "Teknisyen",
    "Teknoloji uzmani",
    "Telefon operatörü",
    "Televizyon tamircisi",
    "Tellal",
    "Temizlikçi",
    "Temsilci",
    "Terapist",
    "Tercüman",
    "Terzi",
    "Tesgahtar",
    "Tesisatçı",
    "Test mühendisi",
    "Test pilotu",
    "Tiyatro yönetmeni",
    "Tornacı",
    "Turizmci",
    "Tuhafiyeci",
    "Turşucu",
    "Uçuş teknisyeni",
    "Ulaşım sorumlusu",
    "Ustabaşı",
    "Uydu antenci",
    "Uzay mühendisi",
    "Uzay bilimcisi",
    "Ürolog",
    "Ütücü",
    "Vaiz",
    "Veritabanı yöneticisi",
    "Veteriner hekim",
    "Veteriner sağlık teknikeri",
    "Veteriner sağlık teknisyeni",
    "Veznedar",
    "Video editörü",
    "Vinç operatörü",
    "Vitrinci",
    "Viyolonselci",
    "Vale",
    "Yatırım uzmanı",
    "Yayıncı",
    "Yazar",
    "Yazılım mühendisi",
    "Yelkenci",
    "Yüzücü",
    "Yönetmen",
    "Zoolog",
    "Ziraat mühendisi",
  ];

  static List<String> cityData = [
    "İstanbul",
    "Ankara",
    "İzmir",
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Aksaray",
    "Amasya",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bartın",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Düzce",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkari",
    "Hatay",
    "Iğdır",
    "Isparta",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kırıkkale",
    "Kırklareli",
    "Kırşehir",
    "Kilis",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Şırnak",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Şanlıurfa",
    "Uşak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak"
  ];

  static List<String> getSuggestions(String pattern) =>
      List.of(jobData).where((element) {
        final itemLower = element.toLowerCase();
        final queryLower = pattern.toLowerCase();
        return itemLower.startsWith(queryLower);
      }).toList();

  static List<String> getCitySuggestions(String pattern) =>
      List.of(cityData).where((element) {
        final itemLower = element.toLowerCase();
        final queryLower = pattern.toLowerCase();
        return itemLower.startsWith(queryLower);
      }).toList();
}
